// use-react-demo/src/App.tsx
import React, { useEffect } from 'react';
import './App.css';
import RemoteBaseComponent from './RemoteBaseComponent';

function App() {

  const handleClick = () => {
    console.log('click')
  }

  return (
    <div className="App">
      <RemoteBaseComponent type="button" text="提交" handleClick={handleClick}></RemoteBaseComponent>
    </div>
  );
}

export default App;

// use-vue-demo/src/App.vue
<template>
    <RemoteBaseComponent type="button" text="提交" v-on:handleClick="handleClick"/>
</template>

<script>
import RemoteBaseComponent from './components/RemoteBaseComponent.vue';

export default {
  name: 'App',
  components: {
    RemoteBaseComponent,
  },
  data() {
    return {
    }
  },
  methods: {
    handleClick() {
      console.log('click');
    }
  }
}
</script>

<style>

</style>
